#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

if ! cloneMesh ../../../../multiphase/interFoam/RAS/propeller .
then
    ./Allmesh
else
    runApplication decomposePar -noFields
fi

runApplication -a decomposePar -fields -copyZero

runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar

# ------------------------------------------------------------------------------